name: media

services:
  app:
    build: ./app
    command: gunicorn app:app --bind 0.0.0.0:8000 --access-logfile=- --error-logfile=-
    volumes:
      - ./app/instance:/app/instance
      - ./media:/media
    env_file:
      - .env
    depends_on:
      - tailscale
    network_mode: service:tailscale

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./media:/media:ro
    depends_on:
      - tailscale
    network_mode: service:tailscale

  tailscale:
    image: tailscale/tailscale:latest
    hostname: media
    env_file: .env
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SERVE_CONFIG=/config/ts-serve.json
    volumes:
      - ./tailscale_var_lib:/var/lib
      - ./config:/config
      - /dev/net/tun:/dev/net/tun
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - net_admin
      - sys_module